[general]
import = [ "theme-gruvbox.toml" ]

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
size = 10.5

[[keyboard.bindings]]
key = "с"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "м"
mods = "Control|Shift"
action = "Paste"
